"""Minimal distributed utilities stub for projected-gan.

This file is auto-generated by setup_projgan.py to provide an
``InfiniteSampler`` that works without inheriting from
``torch.utils.data.Sampler``.
"""

import torch
import numpy as np


class InfiniteSampler:
    """Wraps a dataset index sampler that loops forever."""

    def __init__(self, dataset, rank=0, num_replicas=1, shuffle=True, seed=0, window_size=0.5):
        assert len(dataset) > 0
        self.dataset = dataset
        self.rank = rank
        self.num_replicas = num_replicas
        self.shuffle = shuffle
        self.seed = seed
        self.window_size = window_size

    def __iter__(self):
        order = np.arange(len(self.dataset))
        rnd = None
        window = int(np.rint(order.size * self.window_size))
        epoch = 0
        while True:
            if self.shuffle:
                rnd = np.random.RandomState(seed=self.seed + epoch)
                rnd.shuffle(order)
                epoch += 1
            idx = 0
            while idx < order.size:
                i = idx % order.size
                if window >= 2:
                    j = (i - rnd.randint(window)) % order.size if rnd is not None else i
                else:
                    j = i
                if j % self.num_replicas == self.rank:
                    yield order[j]
                idx += 1
